# -*- coding: utf-8 -*-
"""융과.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PumeaX80RBemv0JsKrCWC1BFxddZyZ_s

[streamlit api reference](https://docs.streamlit.io/library/api-reference)

[docs](https://docs.google.com/document/d/1Kgb8JMvjJ_d0jKn4i_PcrOiTDMfe4Be4OgaQfFLmc-A/edit)
"""

!pip install streamlit -q

!pip install pyngrok

from google.colab import drive
drive.mount('/content/drive')

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import matplotlib.font_manager as fm
# import seaborn as sns
# import plotly.express as px
# from PIL import Image
# 
# sb = st.sidebar
# 
# menu = sb.radio('**목차**', ('주제', '서론', '본론1', '본론2', '결론'))
# 
# 
# ###주제###
# if menu == '주제':
#   st.caption("융합과학 자유주제 탐구 보고서 - 30702 김채은")
#   st.title(":blue[스마트 패션]은")
# 
#   col1, col2, col3 = st.columns([3, 3, 1])
# 
#   with col1:
#     st.subheader('신체 데이터를 어떻게:a  수집하는 것이고,')
#     st.markdown(':wrench:공학 & :stethoscope:생명과학')
# 
#   with col2:
#     st.subheader('생활 속에서 어떻게:a 활용될 수 있을까?')
#     st.markdown(':bar_chart:데이터과학 & :bulb:마케팅', help="관련 논문에서도 분야가 '융복합학'으로 제시되기도 한다.")
# 
#   with col3:
#     st.write(" ")
# 
#   st.divider()
# 
#   #image = Image.open('/content/drive/MyDrive/streamlitQR.jpg')
#   #st.image(image, caption='웹앱 QR코드', width=100)
# 
#   st.markdown('이 발표자료는 데이터 분석을 위한 웹앱을 쉽게 만들어주는 파이썬 라이브러리, :a **:red[streamlit]** 으로 만들어졌습니다.')
# 
#   with st.expander("See code"):
#     code = '''if menu == 'INTRO':
#   st.title(":blue[스마트 패션]은")
# 
#   col1, col2 = st.columns(2)
# 
#   with col1:
#     st.subheader('신체 데이터를:a 어떻게 수집하는 것이고,')
#     st.markdown(':wrench:공학 & :stethoscope:생명과학')
# 
#   with col2:
#     st.subheader('생활 속에서:a 어떻게 활용될 수 있을까?')
#     st.markdown(':bar_chart:데이터과학 & :bulb:마케팅', help="관련 논문에서도 분야가 '융복합학'으로 제시되기도 한다.")
# 
#   st.divider()
# 
#   st.markdown('이 발표자료는 데이터 분석을 위한 웹앱을 쉽게 만들어주는 파이썬 라이브러리, :a **:red[streamlit]** 으로 만들어졌습니다.')'''
#     st.code(code, language='python')
# 
# 
# ###서론###
# elif menu == '서론':
#   st.caption("스마트 패션은 신체 데이터를 어떻게 수집하는 것이고, 생활 속에서 어떻게 활용될 수 있을까?")
# 
#   st.header("연구의 필요성")
# 
#   colll1, colll2 = st.columns(2)
# 
#   with colll1:
#     st.subheader('선행연구')
#     st.markdown('스마트 패션은 주로 의료나 체육 분야에서 유용하게 사용되고 있다. 하지만 블루투스 이어폰, 스마트 워치 등을 제외하면 아직 생활속에 녹아들지는 못했다.')
#     st.markdown('이에 스마트 웨어러블 패션브랜드 확장 전략을 분석한 선행연구가 있다.')
#     st.image('https://www.dbpia.co.kr/img_cover/is_Cover/is_223014b.jpg', caption="김주희, 김유경.(2018).스마트 웨어러블 패션브랜드 융복합 확장 전략에 관한 연구.한국과학예술융합학회,35(),109-120.")
# 
#   with colll2:
#     st.subheader('연구동기')
#     st.markdown("애플 사에서 개발 중에 있는 MR글래스, 스마트 반지 등이 사내에서 회의론을 마주하고 있다는 뉴스 기사를 보고, :blue[스마트 패션이 더욱 활성화 될 수 있는 방안]을 찾아보고 싶었다.")
#     st.image('https://www.thedailypost.kr/news/photo/202303/92217_89618_1128.png', caption="출시 임박 애플 'MR 헤드셋'....내부에서 우려의 목소리, THE DAILYPOST")
#     st.markdown("특히, 가까운 미래에 기술이 더 발전했을 때 주요 소비자 층이 될 수 있을 :blue[현재의 고등학생]을 대상으로 수요를 분석하고 마케팅 전략을 세워보고자 한다.")
# 
#   st.markdown("* 따라서 연구의 필요성을 정리하면 다음과 같다.")
# 
#   st.subheader(":book: 지식 습득")
#   st.markdown('검출 가능한 신체의 작용과 센서의 원리를 이해하여 :a 스마트 패션의 다양한 기능을 알아보면서 :blue[여러 분야의 과학 지식을 습득]하고자 한다.')
# 
#   st.subheader(":bulb: 문제 분석&해결")
#   st.markdown('스마트 패션이 :blue[특정 연령대나 분야 외에서는 잘 사용되지 않는다는 한계]의 :a 극복방안을 탐색할 것이다.')
# 
#   st.subheader(":bar_chart: 데이터마인드 함양")
#   st.markdown('이번 탐구를 통해 데이터 마인드, 즉 :blue[데이터를 발견하여 제대로 이해하고 :a 현상을 개선하고자 하는 마음가짐]을 함양하고 알리고자 한다.')
# 
#   st.header("소주제 추출")
#   st.markdown('① 스마트 패션이 신체 데이터를 수집하는 원리')
#   st.markdown('② 스마트 패션 산업 활성화를 위한 방안 탐색')
# 
# 
# ###본론1###
# elif menu == '본론1':
#   st.caption("스마트 패션은 신체 데이터를 어떻게 수집하는 것이고, 생활 속에서 어떻게 활용될 수 있을까?")
# 
#   st.header("① :a 스마트 패션이 신체 데이터를 수집하는 원리")
#   st.markdown("* 스마트 패션에 사용되는 대표적인 센서 세 가지를 통해 :a 신체에서 어떤 일이 일어나는지, 그것을 어떤 방식으로 수집하는지를 학습한다.")
#   tab1, tab2, tab3 = st.tabs(["심박수 센서", "심전도 센서", "스트레치 센서"])
# 
#   with tab1:
#    st.subheader("심박수 센서란?")
#    st.markdown('대부분의 스마트 워치에는 심박수를 측정할 수 있는 기능이 있다.')
#    st.markdown('심박수는 보통 요골동맥에서 측정한다. 맥박은 어느 동맥에서나 측정할 수 있지만, 확인하기 편한 위치이므로 요골동맥이 일반적으로 사용된다.', help="동맥은 심장에서 나온 혈액을 운반하는 혈관, 정맥은 심장으로 들어가는 혈액을 운반하는 혈관이다. 정맥의 경우 압력이 낮아 심박수를 확인할 수 없지만, 생체인증수단으로 사용되기도 한다.")
#    st.markdown('혈액은 적색광을 반사하고 녹색광을 흡수하여 붉은 색으로 보인다. 이를 활용한 것이 **광학 심박 센서** 이다. 녹색 LED 표시등과 광다이오드를 사용하면 손목의 혈류량을 감지할 수 있다.')
#    st.markdown('손목의 혈류량과 녹색광의 흡수량은 비례하게되므로 초당 수백 번 LED 라이트를 깜박여서 분당 심장이 뛴 횟수, 즉 심박수를 계산한다.')
#    st.markdown('산소와 결합한 헤모글로빈은 적외선을 더 흡수하기 때문에, 적외선 LED도 함께 있다면 동일한 원리로 혈중산소포화도를 측정할 수 있다.')
#    st.image('https://support.apple.com/library/content/dam/edam/applecare/images/ko_KR/applewatch/apple-watch-series6-measure-sensors.png', caption='Apple 고객지원-Apple Watch로 심박수 모니터링하기')
#    st.caption('참고문헌')
#    st.caption('''
#    https://terms.naver.com/entry.naver?docId=496068&cid=60408&categoryId=55558
#    :a https://live.lge.co.kr/smartwatch_tech/
#    :a https://www.yna.co.kr/view/AKR20210915061600009
#    :a https://support.apple.com/ko-kr/HT204666
#    ''')
# 
#   with tab2:
#    st.subheader("심전도 센서란?")
#    st.markdown('심전도 센서는 일반적으로 병원이나 진료소에서 사용된다. 심전도 센서는 심박수, 심장 리듬, 심장의 전기 활동 등을 측정하여 파형 이상을 확인하고 심장 질환을 진단하는 데 사용할 수 있다.')
#    st.markdown('''
#    의료기관에서는 표준 12유도 심전도 검사를 실시한다. 12유도 심전도는 심장의 전기 신호를 손, 발, 가슴, 식도에서 12개의 파형으로 기록하여 심장에 이상이 있는지 정확하게 파악할 수 있다.
#    :a 하지만 스마트 워치는 측정에 한계가 있으므로 하나의 파형만 기록한다. 단일 유도 심전도는 심박수와 규칙성을 측정하며, 높은 민감도로 심방세동을 분류할 수 있다. 심장마비와 같은 기타 질환을 식별하는 데는 사용할 수 없다는 한계가 있다.
#    ''')
#    st.markdown("심장이 규칙적이게 뛰는 경우 '동리듬', 불규칙적인 경우 '심방세동'이라고 한다. 스마트 워치가 심방세동을 감지한 경우 의료기관에서 정확한 진단을 받을 수 있도록 안내한다.")
#    st.image('https://ifh.cc/g/ZJMPWC.jpg', caption='심전도 검사를 위한 전극의 위치')
#    st.image('https://ifh.cc/g/Lj9RJT.jpg', caption='표준 12유도 심전도')
#    st.caption('참고문헌')
#    st.caption('''
#    https://support.apple.com/ko-kr/HT208955
#    :a https://terms.naver.com/entry.naver?docId=333073&cid=60261&categoryId=60261
#    :a https://terms.naver.com/entry.naver?docId=2119573&cid=51007&categoryId=51007
#    ''')
# 
#   with tab3:
#    st.subheader("스트레치 센서란?")
#    st.markdown("스트레치 센서는 신체의 움직임을 감지하며 관절 및 근육 운동 모니터링에 매우 유용하다. 자세교정의 기능이 있는 웨어러블 기기에 사용되기도 한다.")
#    st.markdown("전도성 고무, 즉 금속 혹은 탄소 성분으로, 대개 얇고 신축성이 뛰어나기 때문에 의류에 포함되기 좋다.")
#    st.markdown("센서가 늘어나면 저항이 증가하고, 이를 전압 또는 전류의 변화로 측정한 후 길이의 변화로 인식하는 방식이다.")
#    st.image('https://media.licdn.com/dms/image/C5612AQGdG3OYG5S4yA/article-cover_image-shrink_720_1280/0/1520159365172?e=2147483647&v=beta&t=B7KbuA8972wW2k-sQ2TChC9yN-O6HHFN6IT4jJmhAco', caption='https://www.linkedin.com/pulse/wearable-stretch-sensors-making-underwear-2017-shin-jeong-park')
#    st.caption('참고문헌')
#    st.caption('''
#    http://koreascience.or.kr/article/JAKO202105360034763.pdf
#    :a https://patents.google.com/patent/KR101673531B1/ko
#    :a
#    ''')
# 
# 
# ###본론2###
# elif menu == '본론2':
#   st.caption("스마트 패션은 신체 데이터를 어떻게 수집하는 것이고, 생활 속에서 어떻게 활용될 수 있을까?")
#   st.header("② :a 스마트 패션 산업 활성화를 위한 방안 탐색")
# 
#   df = pd.read_csv('/content/drive/MyDrive/survey.csv')
# 
#   st.markdown("* 설문조사를 실시하여 스마트 패션에 관한 학생들의 수요를 파악했다.")
#   st.markdown("대  상: 성화여자고등학교 1-3학년생 72명 :a 기  간: 2023.04.18~2023.04.25")
# 
#   if st.checkbox('Raw data'):
#     df.columns = ['타임스탬프', '사용실태', '수집긍정도', '안구매이유', '추후의향']
#     st.write(df)
# 
#   plt.rc('font', family='NanumBarunGothic')
# 
#   if st.checkbox('Ⅰ 어떤 스마트 패션(웨어러블 기기)를 사용하시나요?'):
# 
#     df_def01_1 = df['사용실태'].value_counts()
#     fig01_1 = px.bar(df_def01_1, x='사용실태', orientation='h')
#     st.write(fig01_1)
# 
#     df_def01_2 = pd.DataFrame({"사용실태": [65, 12, 7, 0]}, index = ["무선 이어폰/헤드셋", "스마트 워치", "사용하지 않음","기타(의료용 기기 등)"])
#     fig01_2 = px.bar(df_def01_2, x='사용실태', orientation='h')
#     st.write(fig01_2)
# 
# 
#   if st.checkbox('Ⅱ 스마트 패션으로 신체 데이터를 수집하는 것에 대해 어떻게 생각하시나요?'):
# 
#     df_def02 = df['수집긍정도'].value_counts()
#     #st.write(df_def02)
# 
#     st.bar_chart(df_def02)
#     st.markdown("* '1(부정)~5(긍정)")
# 
#     with st.expander("물론 보안 마케팅은 중요하다: 애플의 사례"):
#       st.image("https://imgnews.pstatic.net/image/031/2023/05/25/0000748514_001_20230525113701069.gif?type=w647")
#       st.caption('"내 생리 주기 누가 아는 거 아냐?"…애플, 특별한 광고로 "데이터 보호" 강조(아이뉴스) :a https://n.news.naver.com/mnews/article/031/0000748514?sid=105')
# 
# 
#   if st.checkbox('Ⅲ 웨어러블 기기를 (새롭게 혹은 추가로) 구매하지 않는 이유는 무엇인가요?'):
#     # df_def03 = df['웨어러블 기기를 (새롭게 혹은 추가로) 구매하지 않는 이유는 무엇인가요?'].value_counts()
#     # st.write(df_def03)
#     labels = '높은 가격', '필요성 낮음', '무관심', '불편함', '디자인', '전자파'
#     sizes = [57, 19, 10, 4, 2, 1]
#     fig1, ax1 = plt.subplots()
#     ax1.pie(sizes, labels=labels, autopct='%.0f%%', startangle=90, colors=['#ff595e', '#ffca3a', '#8ac926', '#1982c4', '#6a4c93', '#adb5bd'], textprops={'size': 5})
#     st.pyplot(fig1)
#     st.markdown("* 중복 응답을 허용했다.")
#     st.markdown("* '보안이 우려됨' 항목에는 응답이 없었다.")
# 
#   if st.checkbox('Ⅳ 미래에 MR글래스·스마트 반지와 같은 스마트 패션을 구매할 의향이 있으신가요?'):
# 
#     df_def04 = df['추후의향'].value_counts()
#     #st.write(df_def04)
#     st.bar_chart(df_def04)
#     st.markdown("* '1(부정)~5(긍정)")
# 
#   if st.checkbox('추가 분석'):
#     #st.dataframe(df[['수집긍정도', '추후의향']].groupby(['수집긍정도'], as_index=True).mean().sort_values(by='추후의향', ascending=False))
# 
#     st.markdown("* 추후 구매 의향이 있는 학생이 데이터 수집에도 긍정적일까?")
# 
#     st.set_option('deprecation.showPyplotGlobalUse', False)
#     g = sns.FacetGrid(df, col='추후의향')
#     g.map(plt.hist, '수집긍정도', bins=20)
#     st.pyplot()
# 
# 
# 
# elif menu == '결론':
#   st.caption("스마트 패션은 신체 데이터를 어떻게 수집하는 것이고, 생활 속에서 어떻게 활용될 수 있을까?")
# 
#   st.header("결론")
#   st.markdown('* 스마트 패션은 심박수 센서, 스트레치 센서 등 다양한 센서를 통해 신체 데이터를 수집한다. :a 이때 각 센서가 어떤 신체 변화를 어떤 기본 센서로 감지할 수 있는지를 알 수 있었다.')
#   st.markdown('* 스마트 패션 산업 활성화를 위해 분석한 현재 고등학생들의 스마트 패션에 대한 수요 특징은 다음과 같다.')
#   st.markdown('① 가격에 매우 민감하다. :a ▷ 가격을 낮출 요소를 찾고, 제품의 가격이 합리적이라면 이를 마케팅 포인트로 삼는다.')
#   st.markdown('② 데이터가 수집된다는 사실이나 보안에는 민감하지 않다. :a ▷ 학생 대상 마케팅에서는 이를 강조할 필요성이 떨어진다.')
#   st.markdown('③ 스마트 패션의 필요성을 느끼지 못하는 경우가 있다. :a ▷ 일상적인 신체 데이터 수집의 유익함을 알릴 필요가 있다.')
# 
#   coll1, coll2 = st.columns(2)
# 
#   with coll1:
#     st.subheader("제한점")
#     st.markdown('* 데이터가 적어 분석이 어려웠다.')
#     st.markdown('* 스마트 패션의 필요성을 강조할 구체적인 방안을 제시하지 못했다.')
# 
#   with coll2:
#     st.subheader("보완점")
#     st.markdown('* 표본집단을 확대하여 설문조사를 진행할 수 있다.')
#     st.markdown('* 데이터 마인드와 관련해 스마트 패션의 필요성을 알리는 자료를 제작할 수 있다.')
# 
#   st.subheader("향후 연구과제")
#   st.markdown('* 다른 연령층을 대상으로 동일한 설문조사를 진행하면 어떤 결과가 나올까?')
#   st.markdown('* 기본적인 센서를 활용하여 신체 데이터를 수집하는 장치를 새롭게 고안해보자.')
#   st.markdown('* 스마트 패션의 가격을 낮추기 위한 기술에는 어떤 것이 있을까?')
# 
#   st.subheader("주요 참고 문헌")
#   st.markdown("* 사용자의 신체에 대한 데이터를 활용하는 장치 및 방법, 대구경북과학기술원")
#   st.markdown("특허 문서인 만큼 다양한 선행연구가 제시되었을 뿐만 아니라, 이번 탐구에서는 다루지 않은 신체 데이터를 활용하는 시스템의 원리까지 심화적인 내용도 확인할 수 있다.")
#   st.caption("https://patents.google.com/patent/KR101876618B1/ko")

"""[csv 불러오는 방법](https://velog.io/@anjaekk/Python-Pandas-Streamlit%EB%A1%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%8B%9C%EA%B0%81%ED%99%94-%ED%95%98%EA%B8%B0)

"""

!ngrok authtoken 2OqqBwE62HGvpRHGMDN0ccOrQC4_3WhZq4RiwGLjSB8cAeocT

from pyngrok import ngrok

!streamlit run app.py&>/dev.null&
pub = ngrok.connect(addr='8501')
pub

!ngrok diagnose

#ngrok.kill()